In [16]:
import os
import matplotlib.pyplot as plt
import numpy as np
from numpy import pi
import glob
from matplotlib.pyplot import figure
from os.path import expanduser
home = expanduser("~")
from pymatgen.analysis.ferroelectricity.polarization import Polarization
from pymatgen.util.coord import get_angle
from pymatgen.core.structure import Structure
from pymatgen.core.structure import Lattice
import pymatgen.io.vasp.outputs as vo
from pymatgen.io.vasp.outputs import Outcar
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

In [19]:
path = f"{home}/nn9301k/CuFeS2/pbesol/pbesol/dftu4/7/A221/shear/"
poscar0 = Structure.from_file(path + "CONTCAR111.vasp")
poscar0

Structure Summary
Lattice
    abc : 5.2579674721 5.2579674721 10.4108543396
 angles : 90.0 90.0 90.0
 volume : 287.8207896332496
      A : 5.2579674721 0.0 0.0
      B : 0.0 5.2579674721 0.0
      C : 0.0 0.0 10.4108543396
PeriodicSite: S (1.3267, 1.3145, 1.3014) [0.2523, 0.2500, 0.1250]
PeriodicSite: S (3.9313, 3.9435, 1.3014) [0.7477, 0.7500, 0.1250]
PeriodicSite: S (1.3145, 3.9313, 9.1095) [0.2500, 0.7477, 0.8750]
PeriodicSite: S (3.9435, 1.3267, 9.1095) [0.7500, 0.2523, 0.8750]
PeriodicSite: S (1.3023, 1.3145, 6.5068) [0.2477, 0.2500, 0.6250]
PeriodicSite: S (3.9556, 3.9435, 6.5068) [0.7523, 0.7500, 0.6250]
PeriodicSite: S (3.9435, 1.3023, 3.9041) [0.7500, 0.2477, 0.3750]
PeriodicSite: S (1.3145, 3.9556, 3.9041) [0.2500, 0.7523, 0.3750]
PeriodicSite: Cu (0.0000, 0.0000, 5.2054) [0.0000, 0.0000, 0.5000]
PeriodicSite: Cu (2.6290, 0.0000, 2.6027) [0.5000, 0.0000, 0.2500]
PeriodicSite: Cu (2.6290, 2.6290, 0.0000) [0.5000, 0.5000, 0.0000]
PeriodicSite: Cu (0.0000, 2.6290, 7.8081) [0.000

In [5]:
frac0 = poscar0.frac_coords
cart0 = poscar0.cart_coords
cart0

array([[1.32666101, 1.31449179, 1.30135672],
       [3.931306  , 3.94347529, 1.30135672],
       [1.31449179, 3.931306  , 9.10949692],
       [3.94347529, 1.32666101, 9.10949692],
       [1.3023225 , 1.31449179, 6.50678334],
       [3.95564459, 3.94347529, 6.50678334],
       [3.94347529, 1.3023225 , 3.90407007],
       [1.31449179, 3.95564459, 3.90407007],
       [0.        , 0.        , 5.20542686],
       [2.62898358, 0.        , 2.60271343],
       [2.62898358, 2.62898358, 0.        ],
       [0.        , 2.62898358, 7.80814013],
       [0.        , 0.        , 0.        ],
       [2.62898358, 0.        , 7.80814013],
       [2.62898358, 2.62898358, 5.20542686],
       [0.        , 2.62898358, 2.60271343]])

In [6]:
poscar89 = Structure.from_file(f"{home}/nn9301k/CuFeS2/pbesol/pbesol/dftu4/7/A221/shear/ab/80/2/CONTCAR111.vasp")
frac89 = poscar89.frac_coords
cart89 = poscar89.cart_coords
cart89

array([[1.34915501e+00, 1.31491361e+00, 1.29184935e+00],
       [3.99865974e+00, 3.94045330e+00, 1.29184935e+00],
       [1.38149361e+00, 3.92934441e+00, 9.10399476e+00],
       [3.96632123e+00, 1.32602251e+00, 9.10399476e+00],
       [1.32475252e+00, 1.31276985e+00, 6.49994603e+00],
       [4.02306247e+00, 3.94259714e+00, 6.49994603e+00],
       [3.96375222e+00, 1.30166111e+00, 3.89589792e+00],
       [1.38406254e+00, 3.95370604e+00, 3.89589792e+00],
       [0.00000000e+00, 0.00000000e+00, 5.21689557e+00],
       [2.62808307e+00, 0.00000000e+00, 2.61284715e+00],
       [2.67390746e+00, 2.62768353e+00, 8.79875775e-03],
       [4.58243863e-02, 2.62768353e+00, 7.82094430e+00],
       [0.00000000e+00, 0.00000000e+00, 1.15511748e-02],
       [2.62808307e+00, 0.00000000e+00, 7.82369655e+00],
       [2.67390746e+00, 2.62768353e+00, 5.21964782e+00],
       [4.58243863e-02, 2.62768353e+00, 2.61559971e+00]])

In [7]:
delta_frac89 = frac89 - frac0
pd.DataFrame(delta_frac89)
delta_frac89

array([[ 3.337000e-06,  2.039520e-04, -9.768390e-04],
       [-3.338000e-06, -2.039670e-04, -9.768390e-04],
       [-2.039670e-04, -3.338000e-06, -9.768600e-04],
       [ 2.039670e-04,  3.337000e-06, -9.768600e-04],
       [-3.308000e-06, -2.039670e-04, -9.768600e-04],
       [ 3.338000e-06,  2.039670e-04, -9.768600e-04],
       [-2.039670e-04, -3.308000e-06, -9.768310e-04],
       [ 2.039520e-04,  3.338000e-06, -9.768310e-04],
       [ 0.000000e+00,  0.000000e+00,  8.446870e-04],
       [ 0.000000e+00,  0.000000e+00,  8.447020e-04],
       [ 0.000000e+00,  0.000000e+00,  8.447190e-04],
       [ 0.000000e+00,  0.000000e+00,  8.447170e-04],
       [ 0.000000e+00,  0.000000e+00,  1.108963e-03],
       [ 0.000000e+00,  0.000000e+00,  1.108945e-03],
       [ 0.000000e+00,  0.000000e+00,  1.108915e-03],
       [ 0.000000e+00,  0.000000e+00,  1.108959e-03]])

In [8]:
pd.DataFrame(cart89 - cart0)

0         1         2
0   0.022494  0.000422 -0.009507
1   0.067354 -0.003022 -0.009507
2   0.067002 -0.001962 -0.005502
3   0.022846 -0.000639 -0.005502
4   0.022430 -0.001722 -0.006837
5   0.067418 -0.000878 -0.006837
6   0.020277 -0.000661 -0.008172
7   0.069571 -0.001939 -0.008172
8   0.000000  0.000000  0.011469
9  -0.000901  0.000000  0.010134
10  0.044924 -0.001300  0.008799
11  0.045824 -0.001300  0.012804
12  0.000000  0.000000  0.011551
13 -0.000901  0.000000  0.015556
14  0.044924 -0.001300  0.014221
15  0.045824 -0.001300  0.012886

In [9]:
print(sum(delta_frac89))
print(sum(cart89 - cart0))

[ 1.39999999e-08  1.39999999e-08 -1.73000001e-07]
[ 0.53908662 -0.01560046  0.03738223]


In [87]:
maxi = 21
poscar0.as_dict()['lattice']['c']
for i in range(2, maxi, 2):
    poscari = Structure.from_file(f"{home}/nn9301k/CuFeS2/pbesol/pbesol/dftu4/7/A221/shear/ab/80/{i}/CONTCAR111.vasp")
    delta_frac = poscari.frac_coords  - poscar0.frac_coords
    print(90, " - ", 90 - 0.5*i, "ionic position differences")
    print(pd.DataFrame(delta_frac, columns=['x', 'y', 'z']))
    print("Sum displacements: ", sum(delta_frac), '\n')
    print(poscari.as_dict()['lattice']['c'])

90  -  89.0 ionic position differences
           x         y         z
0   0.000003  0.000204 -0.000977
1  -0.000003 -0.000204 -0.000977
2  -0.000204 -0.000003 -0.000977
3   0.000204  0.000003 -0.000977
4  -0.000003 -0.000204 -0.000977
5   0.000003  0.000204 -0.000977
6  -0.000204 -0.000003 -0.000977
7   0.000204  0.000003 -0.000977
8   0.000000  0.000000  0.000845
9   0.000000  0.000000  0.000845
10  0.000000  0.000000  0.000845
11  0.000000  0.000000  0.000845
12  0.000000  0.000000  0.001109
13  0.000000  0.000000  0.001109
14  0.000000  0.000000  0.001109
15  0.000000  0.000000  0.001109
Sum displacements:  [ 1.39999999e-08  1.39999999e-08 -1.73000001e-07] 

10.4161949158
90  -  88.0 ionic position differences
           x         y         z
0  -0.000008  0.000433 -0.001948
1   0.000008 -0.000433 -0.001948
2  -0.000433  0.000008 -0.001948
3   0.000433 -0.000008 -0.001948
4   0.000008 -0.000433 -0.001948
5  -0.000008  0.000433 -0.001948
6  -0.000433  0.000008 -0.001948
7   0.00043

In [89]:
maxi = 21
poscar0.as_dict()['lattice']['c']
for i in range(2, maxi, 2):
    poscari = Structure.from_file(f"{home}/nn9301k/CuFeS2/pbesol/pbesol/dftu4/7/A221/shear/ab/80/{i}/CONTCAR111.vasp")
    delta_cart = poscari.cart_coords  - poscar0.cart_coords
    print(90, " - ", 90 - 0.5*i, "ionic position differences")
    print(pd.DataFrame(delta_cart, columns=['x', 'y', 'z']))
    print("Sum displacements: ", sum(delta_cart), '\n')
    print(poscari.as_dict()['lattice']['c'])

90  -  89.0 ionic position differences
           x         y         z
0   0.022494  0.000422 -0.009507
1   0.067354 -0.003022 -0.009507
2   0.067002 -0.001962 -0.005502
3   0.022846 -0.000639 -0.005502
4   0.022430 -0.001722 -0.006837
5   0.067418 -0.000878 -0.006837
6   0.020277 -0.000661 -0.008172
7   0.069571 -0.001939 -0.008172
8   0.000000  0.000000  0.011469
9  -0.000901  0.000000  0.010134
10  0.044924 -0.001300  0.008799
11  0.045824 -0.001300  0.012804
12  0.000000  0.000000  0.011551
13 -0.000901  0.000000  0.015556
14  0.044924 -0.001300  0.014221
15  0.045824 -0.001300  0.012886
Sum displacements:  [ 0.53908662 -0.01560046  0.03738223] 

10.4161949158
90  -  88.0 ionic position differences
           x         y         z
0   0.045047  0.000673 -0.019053
1   0.135028 -0.007072 -0.019053
2   0.133961 -0.004741 -0.011579
3   0.046114 -0.001658 -0.011579
4   0.044991 -0.003872 -0.014070
5   0.135084 -0.002527 -0.014070
6   0.040721 -0.001541 -0.016561
7   0.139354 -0.004858 

In [90]:
maxi = 11
frames = []
for i in range(1, maxi):
    if i == 1:
        poscari = Structure.from_file(f"{home}/nn9301k/CuFeS2/pbesol/pbesol/dftu4/7/A221/shear/ac/{90 - i}/rlx/10/CONTCAR111.vasp")
    else:
        poscari = Structure.from_file(f"{home}/nn9301k/CuFeS2/pbesol/pbesol/dftu4/7/A221/shear/ac/{90 - i}/10/CONTCAR111.vasp")
    delta_frac = poscari.frac_coords - poscar0.frac_coords
    print(90, " - ", 90 - i, "ionic position differences")
    frames.append(pd.DataFrame(delta_frac, columns=['x', 'y', 'z']))
    print(pd.DataFrame(delta_frac, columns=['x', 'y', 'z']))
    print("Sum displacements: ", sum(delta_frac), '\n')
    print(poscari.as_dict()['lattice']['b'])

90  -  89 ionic position differences
               x         y             z
0   1.555600e-05 -0.002186  1.820100e-04
1  -1.543800e-05 -0.002186 -1.819960e-04
2   1.500000e-08 -0.001512  6.000000e-08
3   6.000000e-08 -0.001554  6.000000e-08
4  -1.551200e-05 -0.002186 -1.819130e-04
5   1.555700e-05 -0.002186  1.820330e-04
6   6.000000e-08 -0.001512  3.000000e-08
7   1.500000e-08 -0.001554  3.000000e-08
8   9.993300e-01  0.001888 -3.964000e-06
9   6.699860e-04  0.001888  4.009000e-06
10 -6.699260e-04  0.001888  9.999960e-01
11  6.699780e-04  0.001888  4.054000e-06
12  9.996700e-01  0.001832  1.700000e-05
13  3.300010e-04  0.001832 -1.692700e-05
14 -3.299410e-04  0.001832  1.701700e-05
15  3.299860e-04  0.001832 -1.698700e-05
Sum displacements:  [2.00000047e+00 4.61700000e-06 1.00000052e+00] 

5.2581086159
90  -  88 ionic position differences
               x         y             z
0   4.160400e-05 -0.004328  3.500050e-04
1  -4.154400e-05 -0.004328 -3.499910e-04
2   1.500000e-08 -0.0030

In [ ]:
maxi = 21
poscar0.as_dict()['lattice']['c']
for i in range(2, maxi, 2):
    poscari = Structure.from_file(f"{home}/nn9301k/CuFeS2/pbesol/pbesol/dftu4/7/A221/shear/ab/80/{i}/CONTCAR111.vasp")
    delta_cart = poscari.cart_coords  - poscar0.cart_coords
    print(90, " - ", 90 - 0.5*i, "ionic position differences")
    print(pd.DataFrame(delta_cart, columns=['x', 'y', 'z']))
    print("Sum displacements: ", sum(delta_cart), '\n')
    print(poscari.as_dict()['lattice']['c'])

In [15]:
maxi = 11
for i in [-30, -20, -10, 10, 20, 30]:
    poscari = Structure.from_file(f"{home}/nn9301k/CuFeS2/pbesol/pbesol/dftu4/7/A111/abfix/strain{i}/CONTCAR")
    delta_frac = poscari.frac_coords - poscar0.frac_coords
    print(i/10, "ionic position differences")
    print(pd.DataFrame(delta_frac, columns=['x', 'y', 'z']))
    print("Sum displacements: ", sum(delta_frac), '\n')

-3.0 ionic position differences
               x             y             z
0   7.511363e-04  1.500000e-08  7.000000e-09
1  -7.510173e-04  6.000000e-08  7.000000e-09
2   1.500000e-08 -7.510173e-04  6.000000e-08
3   6.000000e-08  7.511363e-04  6.000000e-08
4  -7.510923e-04  1.500000e-08  6.000000e-08
5   7.511363e-04  6.000000e-08  6.000000e-08
6   6.000000e-08 -7.510923e-04  3.000000e-08
7   1.500000e-08  7.511363e-04  3.000000e-08
8   0.000000e+00  0.000000e+00  3.000000e-08
9   3.000000e-08  0.000000e+00  1.500000e-08
10  3.000000e-08  3.000000e-08  0.000000e+00
11  0.000000e+00  3.000000e-08  6.000000e-08
12  0.000000e+00  0.000000e+00  0.000000e+00
13  3.000000e-08  0.000000e+00  6.000000e-08
14  3.000000e-08  3.000000e-08  3.000000e-08
15  0.000000e+00  3.000000e-08  1.500000e-08
Sum displacements:  [4.32999993e-07 4.32999993e-07 5.24000000e-07] 

-2.0 ionic position differences
               x             y             z
0   5.393765e-04  1.500000e-08  7.000000e-09
1  -5.392575

In [11]:
maxi = 11
for i in range(2, maxi, 2):
    poscari = Structure.from_file(f"{home}/nn9301k/CuFeS2/pbesol/pbesol/dftu4/7/A221/shear/ab/80/{i}/CONTCAR111.vasp")
    delta_cart = poscari.cart_coords - poscar0.cart_coords
    print(90 - 0.5*i)
    print(pd.DataFrame(delta_cart, columns=['x', 'y', 'z']))
    print("Sum displacements: ", sum(delta_cart), '\n')

89.0
           x         y         z
0   0.022494  0.000422 -0.009507
1   0.067354 -0.003022 -0.009507
2   0.067002 -0.001962 -0.005502
3   0.022846 -0.000639 -0.005502
4   0.022430 -0.001722 -0.006837
5   0.067418 -0.000878 -0.006837
6   0.020277 -0.000661 -0.008172
7   0.069571 -0.001939 -0.008172
8   0.000000  0.000000  0.011469
9  -0.000901  0.000000  0.010134
10  0.044924 -0.001300  0.008799
11  0.045824 -0.001300  0.012804
12  0.000000  0.000000  0.011551
13 -0.000901  0.000000  0.015556
14  0.044924 -0.001300  0.014221
15  0.045824 -0.001300  0.012886
Sum displacements:  [ 0.53908662 -0.01560046  0.03738223] 

88.0
           x         y         z
0   0.045047  0.000673 -0.019053
1   0.135028 -0.007072 -0.019053
2   0.133961 -0.004741 -0.011579
3   0.046114 -0.001658 -0.011579
4   0.044991 -0.003872 -0.014070
5   0.135084 -0.002527 -0.014070
6   0.040721 -0.001541 -0.016561
7   0.139354 -0.004858 -0.016561
8   0.000000  0.000000  0.022293
9  -0.001601  0.000000  0.019802
10  0.